;---------------------------------
author  = perlancar <perlancar@cpan.org>
copyright_holder = perlancar <perlancar@cpan.org>
license = Perl_5
;---------------------------------

version=0.001

name=Dir-Rename-WD

[@Author::PERLANCAR]
:version=0.610

[Prereqs]
strict=0
warnings=0
Cwd=0
Errno=0
Exporter=5.57
